# Generated by Django 4.2.1 on 2023-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_allowances_commision_saraly_commission_templates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_id', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='addExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.FloatField()),
                ('text', models.CharField(max_length=2000000)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('month', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='employeeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.FloatField()),
                ('employee_name', models.CharField(max_length=255)),
                ('gift_item', models.CharField(max_length=200)),
                ('month', models.DateField()),
                ('award_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.FloatField()),
                ('date', models.DateField()),
                ('Hour', models.DateField()),
                ('Text', models.DateField()),
            ],
        ),
    ]
