# Generated by Django 4.2.1 on 2023-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_first_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='back_id_image',
            field=models.ImageField(default='a.png', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='front_id_image',
            field=models.ImageField(default='a.png', upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(default='a.png', upload_to='pictures'),
        ),
    ]
