# Generated by Django 4.2.1 on 2023-05-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_alter_employees_back_id_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission_templates',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='dailywork',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employeeaward',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='selectdepartment',
            name='select_department',
        ),
        migrations.AddField(
            model_name='selectdepartment',
            name='department',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='first.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancesalary',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
        migrations.AlterField(
            model_name='employeeaward',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.department'),
        ),
        migrations.AlterField(
            model_name='managesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
        migrations.AlterField(
            model_name='payrollsummary',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
    ]
