# Generated by Django 4.2.1 on 2023-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_rename_deductions_salary_details_tax_deductions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywork',
            old_name='employee_name',
            new_name='employee_ID',
        ),
        migrations.RemoveField(
            model_name='dailywork',
            name='commision',
        ),
        migrations.AddField(
            model_name='dailywork',
            name='commision_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
