# Generated by Django 4.2.1 on 2023-06-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_rename_employee_name_dailywork_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission_templates',
            name='commission_policy',
        ),
        migrations.RemoveField(
            model_name='commission_templates',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='commission_templates',
            name='persentage_enjoyed',
        ),
        migrations.AlterField(
            model_name='job_type',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.department'),
        ),
    ]
