# Generated by Django 4.2.1 on 2023-06-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_remove_commission_templates_commission_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managesalary',
            name='employee',
        ),
    ]
