# Generated by Django 4.2.1 on 2023-06-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_remove_managesalary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='managesalary',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managesalary',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.job_type'),
            preserve_default=False,
        ),
    ]
