# Generated by Django 4.2.1 on 2023-06-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_dailywork_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpenses',
            name='text',
            field=models.TextField(),
        ),
    ]
