# Generated by Django 4.2.1 on 2023-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_alter_addexpenses_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpenses',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
