# Generated by Django 4.2.1 on 2023-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_alter_addexpenses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_type',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
