# Generated by Django 4.2.1 on 2023-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_alter_job_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_details',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
