# Generated by Django 4.2.1 on 2023-06-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_alter_salary_details_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywork',
            old_name='job_type',
            new_name='Task',
        ),
    ]
