# Generated by Django 4.2.1 on 2023-06-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_nextofkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='bio_descrption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='employee_lever',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
