# Generated by Django 4.2.1 on 2023-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0023_manager_bio_descrption_manager_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(default='a.png', upload_to='upload'),
        ),
    ]
