# Generated by Django 4.2.1 on 2023-06-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_manager_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission_templates',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission_templates',
            name='job_type',
            field=models.CharField(default='ICT', max_length=255),
            preserve_default=False,
        ),
    ]
