# Generated by Django 4.2.1 on 2023-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_remove_commision_saraly_daily_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commision_saraly',
            name='job_type',
            field=models.CharField(blank='True', max_length=255),
        ),
    ]
