# Generated by Django 4.2.1 on 2023-06-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_remove_commision_rate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DORMANT', 'Dormant')], max_length=50),
        ),
    ]
