# Generated by Django 4.2.1 on 2023-06-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_alter_manager_employee_lever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='commision_rate',
            field=models.FloatField(choices=[('CHOICE A', '35'), ('CHOICE B', '45')]),
        ),
    ]
