# Generated by Django 4.2.1 on 2023-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0035_alter_dailywork_commision_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='commision_rate',
            field=models.FloatField(choices=[('CHOICE A', '25'), ('CHOICE B', '30'), ('CHOICE C', '35'), ('CHOICE D', '40.0'), ('CHOICE B', '45')]),
        ),
    ]
