# Generated by Django 4.2.1 on 2023-06-30 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0037_remove_employees_salary_employees_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='first_employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('Employement_id', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('kra_pin', models.IntegerField()),
                ('image', models.ImageField(default='a.png', upload_to='upload')),
                ('front_id_image', models.ImageField(default='a.png', upload_to='upload')),
                ('back_id_image', models.ImageField(default='a.png', upload_to='upload')),
                ('salary_type', models.CharField(blank=True, choices=[('COMMISION', 'Commision'), ('FIXED', 'Fixed')], max_length=255)),
                ('date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.department')),
            ],
        ),
    ]
