# Generated by Django 4.2.1 on 2023-06-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0039_alter_advancesalary_month_alter_advancesalary_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='date',
        ),
    ]
