# Generated by Django 4.2.1 on 2023-07-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0040_remove_employees_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailywork',
            old_name='Task',
            new_name='job_type',
        ),
    ]
