# Generated by Django 4.2.1 on 2023-07-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0042_alter_dailywork_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.commision_saraly'),
        ),
    ]
