# Generated by Django 4.2.1 on 2023-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0048_alter_dailywork_commision_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
