# Generated by Django 4.2.1 on 2023-07-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0050_alter_dailywork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='commision_rate',
            field=models.IntegerField(),
        ),
    ]
