# Generated by Django 4.2.1 on 2023-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0051_alter_dailywork_commision_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixed_saraly',
            name='daily_work',
        ),
        migrations.RemoveField(
            model_name='fixed_saraly',
            name='monthly_work',
        ),
        migrations.RemoveField(
            model_name='fixed_saraly',
            name='single_work',
        ),
        migrations.AddField(
            model_name='employees',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_middle_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_phone_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
