# Generated by Django 4.2.1 on 2023-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0052_remove_fixed_saraly_daily_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
