# Generated by Django 4.2.1 on 2023-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0053_employees_next_of_kin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalary',
            name='month',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
