# Generated by Django 4.2.1 on 2023-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0054_alter_advancesalary_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpenses',
            name='time',
        ),
        migrations.AlterField(
            model_name='addexpenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
