# Generated by Django 4.2.1 on 2023-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0056_remove_employeeaward_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaward',
            name='award_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
