# Generated by Django 4.2.1 on 2023-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0057_alter_employeeaward_award_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='back_id_image',
            field=models.ImageField(default='a.png', upload_to='first/upload'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='front_id_image',
            field=models.ImageField(default='a.png', upload_to='first/upload'),
        ),
    ]
