# Generated by Django 4.2.1 on 2023-07-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0058_alter_dailywork_date_alter_employees_back_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='total_income',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
