# Generated by Django 4.2.1 on 2023-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0059_employees_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='total_income',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
