# Generated by Django 4.2.1 on 2023-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0060_alter_employees_total_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_initializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidated_employee_income', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
