# Generated by Django 4.2.1 on 2023-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0061_employee_initializer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_initializer',
            name='all_amount_income',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employee_initializer',
            name='company_amount_income',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
