# Generated by Django 4.0.6 on 2023-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0062_employee_initializer_all_amount_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='back_id_image',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='front_id_image',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
    ]
