# Generated by Django 4.0.6 on 2023-08-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0063_alter_employees_back_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
    ]
