# Generated by Django 4.0.6 on 2023-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0065_alter_employees_back_id_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='employee_lever',
            new_name='employee_level',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='kra_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='next_of_kin_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='next_of_kin_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='next_of_kin_middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='next_of_kin_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
