# Generated by Django 4.0.6 on 2023-08-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0066_rename_employee_lever_manager_employee_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, default='null.jpg', null=True, upload_to='upload/'),
        ),
    ]
