# Generated by Django 4.0.6 on 2023-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0068_alter_employees_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='dailywork',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
