# Generated by Django 4.0.6 on 2023-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0069_payslip_dailywork_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywork',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
