# Generated by Django 4.0.6 on 2023-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0074_dailywork_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='financialreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_income', models.IntegerField()),
                ('employee_income', models.IntegerField()),
                ('net_income', models.IntegerField()),
            ],
        ),
    ]
