# Generated by Django 4.2.1 on 2023-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0077_department_employee_view_alter_employees_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='system_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.CharField(max_length=255)),
            ],
        ),
    ]
