# Generated by Django 4.2.1 on 2023-08-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0079_payement_gateway_system_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement_gateway',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='system_payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.employees'),
        ),
    ]
