# Generated by Django 4.2.1 on 2023-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0080_alter_payement_gateway_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_update',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
