# Generated by Django 4.2.1 on 2023-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0081_alter_system_update_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_update',
            name='company_logo',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
    ]
